drop table book;
drop table person;
drop table author;

create table person (
	id int generated by default as identity primary key,
	name character varying(100) NOT NULL UNIQUE,
	year_of_birth int NOT NULL CHECK(year_of_birth > 1900),
	CONSTRAINT NAME_MIN_SIZE CHECK (LENGTH(name)>0)
);
create table author (
	id int generated by default as identity primary key,
	name varchar(100) NOT NULL UNIQUE,
	CONSTRAINT NAME_MIN_SIZE CHECK (LENGTH(name)>0)
);
create table book (
	id int generated by default as identity primary key,
	user_id int REFERENCES person(id) ON UPDATE CASCADE ON DELETE SET NULL,
	name varchar(100) NOT NULL,
	author_id int REFERENCES author(id) ON UPDATE CASCADE ON DELETE CASCADE,
	year int NOT NULL,
	CONSTRAINT NAME_MIN_SIZE CHECK (LENGTH(name)>0)
)